version: '3'
services:
  ws:
    build:
      context: ../..
      dockerfile: docker/rotatepdf_run/Dockerfile
    image: rotatepdf
    user: 1000:1000
    volumes:
      - .:/workspace
    working_dir: /workspace
