version: '3'
services:
  ws:
    build:
      context: ../..
      dockerfile: docker/rotatepdf-cli/Dockerfile
    image: rotatepdf-cli
    user: 1000:1000
    volumes:
      - .:/workspace
    working_dir: /workspace
