version: '3'
services:
  ws:
    build:
      context: .
      dockerfile: Dockerfile
    image: rotatepdf-dev
    user: 1000:1000
    volumes:
      - ${HOME}/.m2:/home/me/.m2
      - ../..:/rotatepdf
    working_dir: /rotatepdf
